#' Estimate an nlmixr2 model loading the model from a targets indirect hash storage
#'
#' This is the command used by the `fit_simple` target generated by
#' [tar_nlmixr()]; it is not typically invoked by end users.
#'
#' @details
#' `object` is the md5 hash returned by [nlmixr_object_simplify()] and stored
#' as the `object_simple` target in the pipeline. `nlmixr2_indirect()` loads
#' the simplified `nlmixrui` object from the `nlmixr2targets` indirect cache
#' (under `<targets store>/user/nlmixr2/`) and passes it to
#' [nlmixr2est::nlmixr()] along with `data`, `est`, and `control`.
#'
#' Routing the simplified ui through a small character-hash target rather than
#' a target whose value is the ui object keeps the dependency hash for the
#' `fit_simple` target independent of large rxUi internals, so cosmetic edits
#' to labels or metadata (which [nlmixr_object_simplify()] strips before
#' caching) do not invalidate the cached fit.
#'
#' @inheritParams nlmixr2est::nlmixr
#' @returns An nlmixr2 fit object, as returned by [nlmixr2est::nlmixr()].
#' @seealso [tar_nlmixr()], [nlmixr_object_simplify()].
#' @export
nlmixr2_indirect <- function(object, data, est, control) {
  nlmixr2est::nlmixr(object = read_nlmixr2obj_indirect(hash = object), data = data, est = est, control = control)
}

# Indirect cache layout
#
# Simplified `nlmixrui` objects are serialized as RDS files keyed by their
# md5 hash. The cache lives next to the targets store so it follows the
# same project-local conventions:
#
#   <tar_config_get("store")>/user/nlmixr2/<md5>
#
# `save_nlmixr2obj_indirect()` writes the object and returns the md5 (which
# the caller passes through targets as a small character target).
# `read_nlmixr2obj_indirect()` loads it back. Both are unexported because
# only `nlmixr_object_simplify()` and `nlmixr2_indirect()` should be touching
# this storage.

read_nlmixr2obj_indirect <- function(hash, directory = file.path(targets::tar_config_get("store"), "user/nlmixr2")) {
  checkmate::assert_string(hash, min.chars = 1)
  path <- file.path(directory, hash)
  if (!file.exists(path)) {
    stop(
      "nlmixr2targets indirect cache miss: no object with hash '", hash,
      "' under '", directory, "'"
    )
  }
  readRDS(path)
}

save_nlmixr2obj_indirect <- function(object, directory = file.path(targets::tar_config_get("store"), "user/nlmixr2")) {
  if (!dir.exists(directory)) {
    dir.create(path = directory, recursive = TRUE)
  }
  saveRDS(object = object, file = file.path(directory, object$md5))
  object$md5
}

#' Inspect the `nlmixr2targets` indirect cache
#'
#' The indirect cache is a directory of serialized, simplified `nlmixrui`
#' objects keyed by md5. It lives under
#' `<targets store>/user/nlmixr2/` and is normally invisible to
#' [targets::tar_destroy()]; these helpers let you inspect and prune it
#' without losing the rest of the `targets` store.
#'
#' @param directory Cache directory. Defaults to
#'   `<targets::tar_config_get("store")>/user/nlmixr2`.
#' @returns A data frame with one row per cached object and columns `hash`
#'   (md5 file name), `size_bytes` (file size), and `mtime` (modification
#'   time). Empty data frame with the same columns if the cache directory
#'   does not exist or is empty.
#' @seealso [nlmixr2targets_cache_prune()] for removing orphaned entries.
#' @export
nlmixr2targets_cache_status <- function(
  directory = file.path(targets::tar_config_get("store"), "user/nlmixr2")
) {
  checkmate::assert_string(directory, min.chars = 1)
  empty <- data.frame(
    hash = character(),
    size_bytes = numeric(),
    mtime = as.POSIXct(character()),
    stringsAsFactors = FALSE
  )
  if (!dir.exists(directory)) {
    return(empty)
  }
  files <- list.files(directory, full.names = TRUE, no.. = TRUE)
  if (!length(files)) {
    return(empty)
  }
  info <- file.info(files)
  data.frame(
    hash = basename(files),
    size_bytes = unname(info$size),
    mtime = info$mtime,
    row.names = NULL,
    stringsAsFactors = FALSE
  )
}

#' Drop orphaned entries from the `nlmixr2targets` indirect cache
#'
#' Removes cache entries whose md5 hash is not in `keep`. By default
#' `dry_run = TRUE`, so the function reports what would be removed without
#' actually deleting anything; pass `dry_run = FALSE` to delete.
#'
#' @details
#' When `keep = NULL`, the function reads the `targets` metadata in the
#' current store and treats every value of a built target whose name ends
#' in `_object_simple` (the hashes produced by [nlmixr_object_simplify()])
#' as reachable. Pass an explicit character vector if you want to override
#' that, e.g. before calling [targets::tar_destroy()] yourself.
#'
#' @param keep Character vector of md5 hashes to retain. If `NULL`
#'   (default), the helper auto-discovers reachable hashes from the
#'   `targets` metadata in the current store. Set to `character()` to
#'   treat every cached entry as an orphan.
#' @param dry_run Logical. If `TRUE` (default), do not delete anything;
#'   just return the hashes that would be removed. If `FALSE`, delete.
#' @param directory Cache directory; same default as
#'   [nlmixr2targets_cache_status()].
#' @returns Invisibly, a character vector of the orphan hashes (those that
#'   were removed when `dry_run = FALSE`, or would be removed otherwise).
#' @seealso [nlmixr2targets_cache_status()].
#' @export
nlmixr2targets_cache_prune <- function(
  keep = NULL,
  dry_run = TRUE,
  directory = file.path(targets::tar_config_get("store"), "user/nlmixr2")
) {
  checkmate::assert_flag(dry_run)
  checkmate::assert_string(directory, min.chars = 1)
  if (!is.null(keep)) {
    checkmate::assert_character(keep, any.missing = FALSE)
  }
  if (!dir.exists(directory)) {
    return(invisible(character()))
  }
  cached <- list.files(directory, no.. = TRUE)
  if (!length(cached)) {
    return(invisible(character()))
  }
  if (is.null(keep)) {
    keep <- .cache_reachable_hashes(
      store = targets::tar_config_get("store")
    )
  }
  orphans <- setdiff(cached, keep)
  if (!dry_run && length(orphans)) {
    file.remove(file.path(directory, orphans))
  }
  invisible(orphans)
}

# Read the targets meta and return the unique values of every built
# `_object_simple` target. These are the md5 hashes that the indirect
# cache must retain for the current pipeline to remain valid.
# Returns character() if there is no targets store or no matching meta.
.cache_reachable_hashes <- function(store = targets::tar_config_get("store")) {
  if (!dir.exists(store)) return(character())
  meta <- tryCatch(
    targets::tar_meta(store = store),
    error = function(e) NULL
  )
  if (is.null(meta) || !nrow(meta)) return(character())
  candidates <- meta$name[grepl("_object_simple$", meta$name)]
  if (!length(candidates)) return(character())
  hashes <- vapply(
    candidates,
    function(n) {
      tryCatch(
        targets::tar_read_raw(n, store = store),
        error = function(e) NA_character_
      )
    },
    FUN.VALUE = NA_character_
  )
  unique(unname(hashes[!is.na(hashes)]))
}
